package com.lteconsulting.offlinedemo.server;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/*
 * The servlet which generates the MANIFEST file
 */
public class ManifestServlet extends HttpServlet
{
	private static final long serialVersionUID = -4114799336246028959L;

	@Override
	protected void doGet( HttpServletRequest req, HttpServletResponse resp ) throws ServletException, IOException
	{
		// Set the appropriate MIME content type
		resp.setContentType( "text/cache-manifest" );

		// set the appropriate headers so that the manifest file is never cached by the browsers
		resp.addHeader( "Cache-Control", "no-cache, must-revalidate" );
		resp.addHeader( "Pragma", "no-cache" );
		resp.addHeader( "Expires", "0" );

		// outputs the manifest file header
		resp.getWriter().println( "CACHE MANIFEST" );
		resp.getWriter().println( "" );
		resp.getWriter().println( "CACHE:" );
		resp.getWriter().println( "" );

		// add the gwt compilation artifacts list file, generated by the AppCacheLinker during the GWT compilation
		readFile( "offlinedemo-artifacts.lst", resp.getWriter() );

		// add other files as required
		readFile( "offlinedemo-other.lst", resp.getWriter() );

		// add all files under the jquery, bootstrap and font-awesome folders
		listFiles( "jquery/", resp.getWriter() );
		listFiles( "bootstrap/", resp.getWriter() );
		listFiles( "font-awesome/", resp.getWriter() );

		// add all files under the pdfs and pictures folders.
		// Those are the files uploaded by the users.
		listFiles( "pdfs/", resp.getWriter() );
		listFiles( "pictures/", resp.getWriter() );

		resp.getWriter().println( "" );
		resp.getWriter().println( "NETWORK:" );
		resp.getWriter().println( "*" );
		resp.getWriter().println( "http://" );
		resp.getWriter().println( "" );
		resp.getWriter().println( "SETTINGS:" );
		resp.getWriter().println( "fast" );
	}

	private void readFile( String name, PrintWriter printWriter ) throws IOException
	{
		try
		{
			BufferedReader in = new BufferedReader( new FileReader( getServletContext().getRealPath( "/" ) + name ) );
			String line;
			while( (line = in.readLine()) != null )
				printWriter.println( line );
			in.close();
		}
		catch(FileNotFoundException e)
		{
		}
	}

	private void listFiles( String directoryPath, PrintWriter printWriter )
	{
		File directory = new File( getServletContext().getRealPath( "/" ) + directoryPath );
		File[] files = directory.listFiles();
		if( files == null )
			return;

		for(int i=0;i<files.length;i++)
		{
			File file = files[i];

			if( file.isDirectory() )
			{
				listFiles( directoryPath + file.getName() + "/", printWriter );
			}
			else
			{
				printWriter.println( directoryPath + file.getName() );
			}
		}
	}
}
